[book]
authors = ["nia"]
language = "zh-CN"
multilingual = false
src = "src"
title = "no title"

[output.html.playground]
editable = true
copyable = true

[output.html]
git-repository-url = "https://github.com/0125nia/nia.github.io"
edit-url-template = "https://github.com/0125nia/nia.github.io/edit/main/{path}"
highlight = { theme = "github" }

[output.html.fold]
enable = true
level = 0
