baseURL = 'https://0125nia.github.io/'
languageCode = 'zh-cn'
title = 'nia'
theme = "gokarna"
enableEmoji = true
pygmentsStyle = "monokai"


[params]
avatarURL = "/avatar.webp"
accentColor = "#FF4D4D"
avatarSize = "size-m"
description = "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué."
footer = "nia"
[menu]
[[menu.main]]
name = "Home"
pre = "<span data-feather='home'></span>"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
pre = "<span data-feather='book'></span>"

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3
pre = "<span data-feather='tag'></span>"

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 4
pre = "<span data-feather='code'></span>"

[[menu.main]]
identifier = "github"
url = "https://github.com/0125nia"
weight = 5
# icons: https://feathericons.com
pre = "<span data-feather='github'></span>"
post = ""

[[menu.main]]
identifier = "juejin"
weight = 6
url = "https://juejin.cn/user/3987308744025273"
pre = "<span data-feather='juejin'></span>"
post = ""

[minify]
minifyOutput = true

[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 3
ordered = false
